name: Checkout Code Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-1
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Check if code is checked out or not
      - name: List files
        run: ls -al

      # Setup Docker Build
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      # Build Docker image with multi-stage build
      - name: Build Docker image
        run: |
          docker build --file Dockerfile --tag my-app-image:latest .

      # 3. Push image to ECR
      - name: Push Docker image to ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_URL }}  # Example: my-app-repo
        run: |
          # Log in to Amazon ECR
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v1n2o2v1

          # Tag the Docker image
          docker tag my-app-image:latest $ECR_REPOSITORY:latest

          # Push the Docker image to ECR
          docker push  $ECR_REPOSITORY:latest    
